version: '2'
services:
  lazaros-postgresql:
    extends:
      file: postgresql.yml
      service: postgresql
    container_name: lazaros-postgresql
  lazaros-minio:
    extends:
      file: minio.yml
      service: minio
    container_name: lazaros-minio
  lazaros-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: elasticsearch
    container_name: lazaros-elasticsearch